src/plugin/addNewBugButton.js
=> #1: Issue URL is hardcoded (closes #1)

src/background/background.js, src/plugin/addNewBugButton.js
=> #4: Make the template prefill timing more reliable (closes #4)

src/plugin/addNewBuildoIssueButton.js
=> #8: UI is wonky on issue page (closes #8)

src/background/background.js, src/manifest.json, src/plugin/addNewBuildoIssueButton.js, src/plugin/plugin.js
=> #9: Make it work with github enterprise (closes #9)

package.json, src/background/background.js, src/plugin/addNewBuildoIssueButton.js, src/plugin/plugin.js, src/plugin/prefillIssueWithTemplate.js, webpack/webpack.base.babel.js
=> #7: Label selections works randomly (closes #7)

src/background/background.js, src/plugin/addSubIssueButton.js, src/plugin/plugin.js, src/plugin/prefillIssueWithTemplate.js
=> #14: 'New sub-issue' button (closes #14)

package.json
=> #26: better npm start for development (closes #26)

src/plugin/addNewBuildoIssueButton.js
=> #28: remove standard button "New Issue" (closes #28)

package.json, src/manifest.json, src/plugin/addMyMilestoneButton.js, src/plugin/addNewBuildoIssueButton.js, src/plugin/plugin.js, webpack/webpack.base.babel.js, webpack/webpack.build.config.babel.js, webpack/webpack.dev.config.babel.js
=> #20: Button with link to my issue of current milestone (closes #20)

src/background/background.js, src/plugin/addNewBuildoIssueButton.js, src/plugin/plugin.js, src/plugin/prefillIssueWithTemplate.js
=> #31: issue options should close on click outside (closes #31)

src/plugin/addSubIssueButton.js, src/plugin/prefillIssueWithTemplate.js
=> #34: Subissue button doesn't work (closes #34)

src/plugin/addNewBuildoIssueButton.js
=> #35: Pressing `⌘+C` should not navigate to new issue page (closes #35)

src/plugin/addSubIssueButton.js, src/plugin/prefillIssueWithTemplate.js
Issue #18
**NB: based on #36**
**test plan**
parent without topic:
parent with topic:
=> #18: sub-issue should keep topic info (closes #18)

src/manifest.json, src/plugin/addGyazoButton.js, src/plugin/plugin.js, src/plugin/styles/plugin.less, src/popup/index.html, src/popup/index.js, src/popup/popup.less, webpack/webpack.base.babel.js
Issue #40
- download Gyazo https://gyazo.com/download?dl=now
- sign up and create `access_token` https://gyazo.com/oauth/applications
- set the `access_token`
- Use gyazo to capture a gif screenshot
- Click on the green button ADD GIF
- have fun!
=> #40: [Screenshots] Shortcut to paste gifs from Gyazo (closes #40)

src/plugin/addNewBuildoIssueButton.js, src/plugin/prefillIssueWithTemplate.js
=> #46: Add generic issue without template (closes #46)

src/plugin/addSubIssueButton.js, src/plugin/prefillIssueWithTemplate.js
=> #48: Subissues should inherit all the labels from the macro (closes #48)

release.js, src/plugin/prefillIssueWithTemplate.js
=> #50: Fix release (closes #50)

src/manifest.json
=> #52: remove update_url from manifest' (closes #52)

src/plugin/addNewBuildoIssueButton.js
=> #54: fix issue buttons bindings (closes #54)

src/plugin/addSubIssueButton.js
=> #58: [subissue] should filter out "customers" label (closes #58)

src/plugin/addNewBuildoIssueButton.js, src/plugin/addSubIssueButton.js
Issue #63
- it should pass project param to nemobot api
=> #63: [nemobot templates] custom templates for project (closes #63)

src/plugin/addElephantReminderButton.js, src/plugin/plugin.js, src/plugin/styles/plugin.less
Issue #68
[![https://gyazo.com/ae479d1d3b1368bfd02c517a457fee74](https://i.gyazo.com/ae479d1d3b1368bfd02c517a457fee74.gif)](https://gyazo.com/ae479d1d3b1368bfd02c517a457fee74)
=> #68: add elephant reminder button (closes #68)
